from building import *
import rtconfig
cwd     = GetCurrentDir()
src	= Glob('CMSIS/DeviceSupport/*.c')
CPPPATH = [cwd + '/CMSIS/CoreSupport', cwd + '/CMSIS/DeviceSupport', cwd + '/SWM181_StdPeriph_Driver']

src += Glob('SWM181_StdPeriph_Driver/*.c')

if rtconfig.CROSS_TOOL == 'gcc':
    src += ['CMSIS/DeviceSupport/startup/gcc/startup_SWM181.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['CMSIS/DeviceSupport/startup/arm/startup_SWM181.s']
elif rtconfig.CROSS_TOOL == 'iar':
    print('Not Support iar now\n')
    exit(0)
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
